---
abstract: 'map/grep arrays and hashes pairwise'
author:
  - 'Thomas Drugeon, <tdrugeon@cpan.org>'
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: List-Pairwise
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.29
